version: '3.8'

services:
  postgres:
    container_name: style-cut-barber-container
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    #volumes:
    #  - ./data/pg:/data/postgres
